### ISSUE TITLE
[Suggestion] CX and Trade Window

### ISSUE THREAD

**Issue by wheatbread** [aramunn/wildstar-easy-plat-entry#1]
Hi!  I really like this addon as it's easier to use than BetterMoneyInput when doing bulk posting on the AH, because this one makes it possible to just copy-paste the prices.  Thank you for making it!

I had a couple suggestions if I may?
1.  Would there be any chance of making it also work for the commodity exchange and trade window?  (Maybe also the CREDD exchange)
2. It would be great if it would register the pasted/ typed in price once you click away, without having to hit enter!  This is because the enter key is far from ctrl+v and slows you down when you're in the pasting bulk posting zone.  :)

**Comment by aramunn** [comment]
Didn't even realize that copy/paste would work lol. What a great feature! Thanks for that info. I'll add it to the curse page.
1. The CX is my next task. It's structured different enough from the AH that my generalized method of hooking into the default cash input windows doesn't quite work. I want to come up with a better way. Once I do adding this to other places should be easy. That's the goal at least.
2. Didn't think about that. I was thinking clicking away would be like hitting cancel, but since this addon doesn't actually hit any buy/sell buttons then that should be ok. Maybe I'll try to make Esc cancel.

I'll update this issue when I add these features. Thank you for the suggestions!

**Comment by aramunn** [comment]
Can't find a way to PM on github. I just found out this addon doesn't actually work... How I missed that I'm still baffled at. Trying to let you know it doesn't take the new price once you enter it. It ends up listing it at the default price. Not sure why. I'll fix it soon. Hopefully you noticed and didn't lose money like I did.

**Comment by aramunn** [comment]
That major bug is fixed in 11.1.0. Now to add support to more cash windows and triple check that Carbine's addons actually accept my inputs instead of just pretending.

**Comment by aramunn** [comment]
Comment 2 above: Added this feature in 11.1.1. It was a quick hack so no escape for cancel yet. That will come with the next major release with all my refactoring changes.

**Comment by wheatbread** [comment]
Re bug: Thanks for letting me know!  I actually hadn't posted anything yet and have now updated with your fixed version.

Re feature, that's great, thanks!

**Comment by aramunn** [comment]
Re comment 1 from your first post: this is added in #4 plus other windows

**Comment by aramunn** [comment]
That's release 11.2.0 on curse
